name: Build and Publish Plugin

on:
  workflow_dispatch:
    inputs:
      publish_plugin_open_vsx:
        description: "Publish Plugin to Open VSX Registry"
        required: false
        default: false
        type: boolean
      publish_plugin_vs_marketplace:
        description: "Publish Plugin to Visual Studio Marketplace"
        required: false
        default: false
        type: boolean

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: false

      - name: Install dependencies
        run: npm ci

      - name: Build Plugin
        run: |
          npm run package
          VSIX_FILE=$(find . -maxdepth 1 -name "*.vsix" | head -n 1)
          echo "VSIX_PATH=$VSIX_FILE" >> $GITHUB_ENV

      - name: Publish Plugin to Open VSX Registry
        if: ${{ fromJSON(github.event.inputs.publish_plugin_open_vsx) }}
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ env.VSIX_PATH }}
          registryUrl: https://open-vsx.org

      - name: Publish Plugin to Visual Studio Marketplace
        if: ${{ fromJSON(github.event.inputs.publish_plugin_vs_marketplace) }}
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ env.VSIX_PATH }}
          registryUrl: https://marketplace.visualstudio.com
